### ISSUE TITLE
Equivalencias

### ISSUE THREAD

**Issue by Noctum98** [Noctum98/Sistema-IES#566]
- [x] Crear migration/model/controller de 'equivalencias'

- [x] Debe contener los campos-> alumno_id / materia_id / nota / fecha / resolucion

- [x] En el sidebar crear una nueva entrada que sea 'Equivalencias' que solo sea visible para quien contenga el rol 'equivalencias' (Crear rol secundario para probar)

- [x] En esta vista debe visualizarse un buscador similar al buscador de alumnos, al traer los resultados debe verse un botón que rediriga a una vista show donde se vean las equivalencias de ese alumno mas un botón de 'Agregar Equivalencia'.

- [X]  Al clickear botón debe abrirse un modal similar al modal de 'Agregar Materias' en el edit de user, es decir que contenga un select con las carreras donde esta inscripto el alumno (AlumnoCarrera es la tabla)
- [X]  Al elegir una rellenar un select secundario con las materias que contiene la carrera y al seleccionar la misma que se puedan cargar los siguientes campos (nota/fecha/resolucion)
- [X] Cambiar que no aparezca el id sino el nombre de la materia. 

Referencias:
Selects en modals: public/js/user/carreras.js | vista: /usuarios/detalle/41

**Comment by gerMdz** [comment]
* Agregar

- [ ]  La opción de eliminar la equivalencia
- [ ]  La opción de eliminar la equivalencia
- [ ]  Enlace en el nombre del alumno para ver el detalle del mismo.

**Comment by gerMdz** [comment]
- [ ] Agregar aviso de borrado
- [ ] Agregar nombre de carrera

**Comment by gerMdz** [comment]
- Regularidad
- [ ]  Crear modelo regularidad

**Comment by gerMdz** [comment]
- Se crea el modelo de regularidad
- [ ]  Crear método que agrega una regularidad de un proceso a otro.

**Comment by gerMdz** [comment]
- Se crea el index de regularidad
- Se buscan los procesos donde el alumno está regular
- [ ]  Crear método que agrega una regularidad de un proceso a otro.

**Comment by gerMdz** [comment]
- [ ] Ver el tema de no repetir proceso anterior
- [ ] Ver el tema de no repetir proceso regularidad anterior
- [ ] Ver copiar condición de procesos ciclos lectivos anteriores
- [ ]  Revisar la lista de procesos de ciclos lectivos
